"use client";

import { AnimatePresence, m, useReducedMotion } from "motion/react";
import { useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { IoCloseOutline } from "react-icons/io5";
import { formatTokenAmount } from "./format";
import { releaseConfig } from "@mozy/chain-config";

export function CancelDialog({ open, openAmount, freeAmount, pending, onClose, onConfirm }: { open: boolean; openAmount: bigint; freeAmount: bigint; pending: boolean; onClose: () => void; onConfirm: () => void }) {
  const reduceMotion = useReducedMotion(); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; const keydown = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onClose(); if (event.key === "Tab") { const nodes = dialog.current?.querySelectorAll<HTMLElement>("button"); if (!nodes?.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", keydown); requestAnimationFrame(() => dialog.current?.querySelector<HTMLElement>("[data-initial]")?.focus()); return () => { document.removeEventListener("keydown", keydown); previous?.focus(); }; }, [onClose, open, pending]);
  if (typeof document === "undefined") return null;
  return createPortal(<AnimatePresence>{open ? <m.div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/20 p-3 sm:items-center" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><m.div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="cancel-title" className="w-full max-w-lg rounded-control border border-line-strong bg-paper-raised shadow-control" initial={{ y: reduceMotion ? 0 : 10 }} animate={{ y: 0 }} exit={{ y: reduceMotion ? 0 : 8 }} transition={{ duration: reduceMotion ? 0 : .18 }}><div className="flex items-center justify-between border-b border-line p-4"><h2 id="cancel-title" className="text-lg font-medium">Cancel open remainder</h2><button type="button" onClick={onClose} disabled={pending} aria-label="Close cancellation" className="min-h-11 min-w-11 text-xl outline-none focus-visible:outline-2 focus-visible:outline-signal"><IoCloseOutline aria-hidden="true" /></button></div><div className="p-5"><dl className="divide-y divide-line border-y border-line"><div className="flex justify-between py-4"><dt>Open TEST removed</dt><dd className="font-mono tabular-nums">{formatTokenAmount(openAmount, releaseConfig.deliveryToken.decimals)}</dd></div><div className="flex justify-between py-4"><dt>BTKT made reclaimable</dt><dd className="font-mono tabular-nums">{formatTokenAmount(freeAmount, releaseConfig.settlementToken.decimals)}</dd></div></dl><p className="mt-5 text-sm leading-6 text-ink-secondary">Active reservations keep their locked quantity and payout until settlement or expiry. Their ability to settle remains unchanged. Reclaiming BTKT is a separate on-chain action.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" data-initial onClick={onClose} disabled={pending} className="min-h-11 rounded-control border border-line-strong px-4 text-sm font-medium">Keep acquisition open</button><button type="button" onClick={onConfirm} disabled={pending} className="min-h-11 rounded-control bg-signal px-4 text-sm font-medium text-paper-raised disabled:bg-line-emphasis">Cancel open remainder</button></div></div></m.div></m.div> : null}</AnimatePresence>, document.body);
}
